### ISSUE TITLE
Package addition for LiveCD?

### ISSUE THREAD

**Issue by ghost** [gobolinux/LiveCD#2]
Not sure if this is the right issue tracker, sorry.

I noticed one thing in the GoboLinux installer on my laptop so far:
- Fluxbox is not included I think :)

Would be nice if this one could be included; AwesomeWM confuses me a lot. That is what I got after "startx".

Do you think that there is enough space for the LiveCD to include Fluxbox? Anyway feel free to close this issue request at any time!

**Comment by hishamhm** [comment]
It's not a matter of space, but a matter of support overhead (configuration, etc). We don't plan to add more window managers to the release ISO. For this reason, I'm closing this one, sorry.

But still, I'd welcome some more feedback: I tried hard to configure AwesomeWM to make it less confusing from the get-go. Which parts were particularly confusing?
