### ISSUE TITLE
Gobo016-Beta - Firefox updates

### ISSUE THREAD

**Issue by Barrocas** [gobolinux/LiveCD#3]
Firefox is now working great, but it does not have permissions to update/upgrade itself with the usual security updates.

![img_20161121_193648](https://cloud.githubusercontent.com/assets/4006691/20521320/9ebdae0a-b0a2-11e6-9871-bdf034807821.jpg)

**Comment by hishamhm** [comment]
All programs in /Programs are owned by root, and Firefox is no exception.
If you want automatic updates, it is up to you to set up more lenient
permissions in your system.

**Comment by Barrocas** [comment]
Hi Hisham,

I have mailed this with Lucas, and placed this here only as a public
placeholder for things to be ordered, so we can work together in
solving any issue, instead of exchanging private emails, and maybe
avoid the same works being duplicated.

I know all /Programs are owned by root, but how did Firefox work with
updates in Gobo 015?

## 

Cumprimentos,
D.er Hugo Barrocas

**Comment by lucasvr** [comment]
This has been addressed and fixed on 016.
