### ISSUE TITLE
Package Listing + Version on gobolinux LiveCD / LiveDVD

### ISSUE THREAD

**Issue by ghost** [gobolinux/LiveCD#7]
Hello lucas and hisham and other gobo-curious folks,

Lucas recently announced a new test release for gobo here:

http://lists.gobolinux.org/pipermail/gobolinux-users/2017-March/009813.html

I downloaded and burned it onto a DVD. All fine so far but I also 
wondered which program versions were included.

E. g. I recently noticed that firefox depends on pulseaudio for audio output
via the browser, at the least the binaries distributed by mozilla (I think you
can change the configure options if you compile it from source e. g. via
--enable-alsa or something like that), so I wanted to see if the DVD
includes pulseaudio or not.

So here is my **suggestion or request**:

- Could there be some text file added somewhere, that could of course
be autogenerated by some script (to make it easier to update it
automatically), **whenever a new gobo CD/DVD** or so **is released**,
that includes the names of the programs and the versions?

For example, a .txt or .md file that would have:

OpenSSL: 1.0.2k
Linux-Firmware: latest git
Firefox: 52.0
Awesome: 4.0

Anyway I think you get the idea. (If no version is provided such as
via git checkout, it could be substituted with the time when the checkout
happened such as ... in ddmmyyyy format or yyyymmdd or something
like that.)

This text file could then be made available somewhere, does not 
matter where, could be a gist file too. When someone installs 
gobolinux or has it burned, it is easy to mount the CD/DVD and
find out, but sometimes people would like to know beforehand 
and this is where I think this suggestion may be helpful.

The names of this (autogenerated) could be generic, such as
"name_of_version_gobo_linux_release_**versioned_program_listing.md**"
or something like that. The name is of course only a suggestion -
giving things a proper name is one of the hardest problem in 
computer science. :)

Anyway, it is not hugely important, feel free to close it at any time.

Thanks for reading!

**Comment by lucasvr** [comment]
Sure, we are used to announce the full list of packages every time we announce a stable release, but I can do it for the ISO candidates too. Thanks for the feedback!

**Comment by lucasvr** [comment]
I ended up opting to attach the list of packages featured on each ISO on GitHub. You are expected to find it there on all releases from now on.
