### ISSUE TITLE
Link to .iso image is missing corresponding .iso.asc signature file, PGP key and .iso.DIGESTS file containing SHA256 hash value for iso image

### ISSUE THREAD

**Issue by MarkRijckenberg** [gobolinux/LiveCD#8]
Hi,

I could not find the corresponding iso.asc signature file and output of the SHA256 hash value for iso image.
From a security and integrity point of view, I think it is very important to have a signature file and SHA256 hash value for each iso image that can be downloaded by the community. (MD5 is too weak, of course). Or else we can not be sure the .iso file has been tampered with by a hacker.

See following links as a reference:

https://www.qubes-os.org/downloads/
https://www.qubes-os.org/security/verifying-signatures/

Regards,

Mark

**Comment by lucasvr** [comment]
Hi Mark.
I've included hashes on our GitHub page and on our downloads page at gobolinux.org -- thanks for reminding us of doing so. The announcement of 016.01 was done very late at night and I just forgot to include that information.
Best regards.

**Comment by MarkRijckenberg** [comment]
Thanks for adding the hashes. It is none of my business, but I would advise removing the MD5 hash result to force people to use SHA256. MD5 is weak and vulnerable to MD5 collision attacks....

**Comment by lucasvr** [comment]
That's good idea. I'm updating the page and the GitHub announcement message now. Thanks!
