### ISSUE TITLE
installation from USB

### ISSUE THREAD

**Issue by mgood7123** [gobolinux/LiveCD#9]
when I try to install via USB flash drive (or micro-sdcard with usb adapter in my case) it tries to mount CD-ROM instead of the usb then fails as it cannot find the files due to CD-ROM not being mounted

**Comment by mgood7123** [comment]
"/proc/ide/hd*/media file not found or does not exist"

**Comment by Barrocas** [comment]
Is your USB adapter trying to be mounted as a CD-Rom so that you can
install some windows drivers or programs contained in that CD-Rom volume
inside the USB adapter?
Then it would switch to USB mode after that instalation.

I have a USB flash drive (U3 Intuix) that used to do that.
The U3 website provided instructions and software to disable the CD-Rom in
the USB drive, now it works fine.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by mgood7123** [comment]
no, on every other distro the adapter always mounts itself as sd* eg sdb or sda depending on if the hard disk mounts itself second when booting from usb but having a third device usually fixes it so hard disk is mounted sda and usbs sdb n sdc, but iv never seen it mount itself as cd-rom nor does it state it is mounted as cdrom when i manually mount it after it drops me into shell after ur mounting error so i assume ur script assumes im installing from cd-rom and not usb

**Comment by mgood7123** [comment]
by the way it is on the Mounting GloboLinux Install CD... section of ur script that gives the error and i am unable to boot into globolinux

**Comment by mgood7123** [comment]
interestingly enough if I type startGloboLinux after being dropped to shell it gives Mounting none at... followed by similar mounting errors like device is busy

**Comment by mgood7123** [comment]
strange how one little mounting error can cause a mountain of problems lol

**Comment by mgood7123** [comment]
also i noticed ur distro uses busybox :/ i dislike busybox cus it has reduced command, is it possible to replace that with the full commands from another distro wich has them?

**Comment by lucasvr** [comment]
We actually attempt at mounting both CD-ROMs and USB devices:
https://github.com/gobolinux/InitRDScripts/blob/master/bin/mountGoboLinux

If for some reason none of the mount commands succeed, you are redirected to a rescue Busybox console that lives in the initrd. Are you able to manually mount it from that console? Do you have a corresponding /dev/ entry for that USB?

**Comment by lucasvr** [comment]
I see that you have opened a new issue at https://github.com/gobolinux/InitRDScripts/issues/1. I'm closing this one so we can track it in a single place.
